name          'yo61-cloudinit'
version       '1.0.1'
source        'https://github.com/yo61/puppet-cloudinit'
author        'Robin Bowes <robin.bowes@yo61.com>'
license       'Apache-2.0'
summary       'Helper to install Amazon Cloudinit scripts'
description   ''
project_page  'https://github.com/yo61/puppet-cloudinit'

dependency 'puppetlabs/stdlib'
